version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      npm-development:
        update-types:
          - "minor"
          - "patch"
        dependency-type: "development"
      npm-production:
        update-types:
          - "minor"
          - "patch"
        dependency-type: "production"
